// Generates 80 realistic sample requisitions for the NS demo
// Covers all status types, multiple TAs, breaches, inferred TATs, unassigned etc.

interface SampleRow {
  ID: string; Req_Raised: string; HR_Approval_Date: string;
  Agreed_TAT: string; Request_DOJ: string; Vacancies: number;
  Status: string; Division: string; Function: string; Designation: string;
  Location: string; Requestor: string; Project: string; TA_Members: string;
  Sourced: number; Shortlisted: number; In_Interview: number;
  Selected: number; Offered: number; Offer_Accepted: number; Joined: number;
}

const ROWS: SampleRow[] = [
  // ─── Data Analytics – Priya Nair ─────────────────────────────────────────
  { ID:'REQ-001', Req_Raised:'2026-01-10', HR_Approval_Date:'2026-01-16', Agreed_TAT:'2026-03-31', Request_DOJ:'', Vacancies:2, Status:'Closed-Filled', Division:'Data Analytics', Function:'Analytics', Designation:'Research Analyst', Location:'Mumbai', Requestor:'Abhijit Gupta', Project:'Client Intel', TA_Members:'Priya Nair', Sourced:42, Shortlisted:11, In_Interview:6, Selected:2, Offered:2, Offer_Accepted:2, Joined:2 },
  { ID:'REQ-002', Req_Raised:'2026-01-18', HR_Approval_Date:'2026-01-24', Agreed_TAT:'2026-04-15', Request_DOJ:'', Vacancies:1, Status:'Closed-Filled', Division:'Data Analytics', Function:'Analytics', Designation:'Senior Research Analyst', Location:'Bangalore', Requestor:'Prashant Mehta', Project:'Retail Insights', TA_Members:'Priya Nair', Sourced:35, Shortlisted:8, In_Interview:4, Selected:1, Offered:1, Offer_Accepted:1, Joined:1 },
  { ID:'REQ-003', Req_Raised:'2026-02-03', HR_Approval_Date:'2026-02-10', Agreed_TAT:'2026-04-30', Request_DOJ:'', Vacancies:3, Status:'In Progress', Division:'Data Analytics', Function:'Analytics', Designation:'Data Analyst', Location:'Mumbai', Requestor:'Abhijit Gupta', Project:'FMCG Dashboard', TA_Members:'Priya Nair', Sourced:58, Shortlisted:14, In_Interview:7, Selected:2, Offered:2, Offer_Accepted:1, Joined:1 },
  { ID:'REQ-004', Req_Raised:'2026-02-15', HR_Approval_Date:'2026-02-20', Agreed_TAT:'2026-04-10', Request_DOJ:'', Vacancies:2, Status:'In Progress', Division:'Data Analytics', Function:'Analytics', Designation:'Senior Data Analyst', Location:'Mumbai', Requestor:'Sonal Kapoor', Project:'E-comm Intelligence', TA_Members:'Priya Nair', Sourced:31, Shortlisted:9, In_Interview:5, Selected:1, Offered:1, Offer_Accepted:0, Joined:0 },
  { ID:'REQ-005', Req_Raised:'2026-03-01', HR_Approval_Date:'2026-03-07', Agreed_TAT:'2026-05-15', Request_DOJ:'', Vacancies:1, Status:'Open', Division:'Data Analytics', Function:'Analytics', Designation:'Analytics Manager', Location:'Bangalore', Requestor:'Deepak Narayan', Project:'Client Intel', TA_Members:'Priya Nair', Sourced:18, Shortlisted:4, In_Interview:2, Selected:0, Offered:0, Offer_Accepted:0, Joined:0 },
  { ID:'REQ-006', Req_Raised:'2026-03-15', HR_Approval_Date:'2026-03-20', Agreed_TAT:'2026-05-30', Request_DOJ:'', Vacancies:2, Status:'Open', Division:'Data Analytics', Function:'Analytics', Designation:'Research Analyst', Location:'Delhi', Requestor:'Prashant Mehta', Project:'BFSI Research', TA_Members:'Priya Nair', Sourced:12, Shortlisted:3, In_Interview:1, Selected:0, Offered:0, Offer_Accepted:0, Joined:0 },
  { ID:'REQ-007', Req_Raised:'2026-04-02', HR_Approval_Date:'2026-04-08', Agreed_TAT:'2026-06-15', Request_DOJ:'', Vacancies:1, Status:'In Progress', Division:'Data Analytics', Function:'Analytics', Designation:'Associate Director – Analytics', Location:'Mumbai', Requestor:'Sonal Kapoor', Project:'Strategic Research', TA_Members:'Priya Nair', Sourced:8, Shortlisted:3, In_Interview:2, Selected:1, Offered:1, Offer_Accepted:1, Joined:0 },
  { ID:'REQ-008', Req_Raised:'2026-04-20', HR_Approval_Date:'2026-04-25', Agreed_TAT:'2026-07-10', Request_DOJ:'', Vacancies:3, Status:'In Progress', Division:'Data Analytics', Function:'Analytics', Designation:'Data Analyst', Location:'Bangalore', Requestor:'Abhijit Gupta', Project:'Retail Insights', TA_Members:'Priya Nair', Sourced:44, Shortlisted:10, In_Interview:5, Selected:2, Offered:2, Offer_Accepted:2, Joined:0 },
  { ID:'REQ-009', Req_Raised:'2026-05-05', HR_Approval_Date:'', Agreed_TAT:'', Request_DOJ:'2026-07-01', Vacancies:1, Status:'Draft/Unapproved', Division:'Data Analytics', Function:'Analytics', Designation:'Senior Research Analyst', Location:'Mumbai', Requestor:'Deepak Narayan', Project:'Client Intel', TA_Members:'', Sourced:0, Shortlisted:0, In_Interview:0, Selected:0, Offered:0, Offer_Accepted:0, Joined:0 },
  { ID:'REQ-010', Req_Raised:'2026-05-18', HR_Approval_Date:'2026-05-22', Agreed_TAT:'2026-08-10', Request_DOJ:'', Vacancies:2, Status:'In Progress', Division:'Data Analytics', Function:'Analytics', Designation:'Research Analyst', Location:'Mumbai', Requestor:'Prashant Mehta', Project:'FMCG Dashboard', TA_Members:'Priya Nair', Sourced:27, Shortlisted:7, In_Interview:3, Selected:1, Offered:1, Offer_Accepted:0, Joined:0 },

  // ─── Data Engineering – Priya Nair ────────────────────────────────────────
  { ID:'REQ-011', Req_Raised:'2026-01-08', HR_Approval_Date:'2026-01-13', Agreed_TAT:'2026-03-20', Request_DOJ:'', Vacancies:2, Status:'Closed-Filled', Division:'Data Engineering', Function:'Engineering', Designation:'Data Engineer', Location:'Bangalore', Requestor:'Rajan Pillai', Project:'Data Platform', TA_Members:'Priya Nair', Sourced:38, Shortlisted:10, In_Interview:5, Selected:2, Offered:2, Offer_Accepted:2, Joined:2 },
  { ID:'REQ-012', Req_Raised:'2026-01-22', HR_Approval_Date:'2026-01-28', Agreed_TAT:'2026-04-05', Request_DOJ:'', Vacancies:1, Status:'Closed-Filled', Division:'Data Engineering', Function:'Engineering', Designation:'Senior Data Engineer', Location:'Bangalore', Requestor:'Rajan Pillai', Project:'Data Platform', TA_Members:'Priya Nair', Sourced:25, Shortlisted:6, In_Interview:3, Selected:1, Offered:1, Offer_Accepted:1, Joined:1 },
  { ID:'REQ-013', Req_Raised:'2026-02-10', HR_Approval_Date:'2026-02-17', Agreed_TAT:'2026-04-15', Request_DOJ:'', Vacancies:3, Status:'In Progress', Division:'Data Engineering', Function:'Engineering', Designation:'Data Engineer', Location:'Hyderabad', Requestor:'Nisha Joshi', Project:'ETL Modernisation', TA_Members:'Priya Nair', Sourced:52, Shortlisted:12, In_Interview:6, Selected:2, Offered:2, Offer_Accepted:1, Joined:0 },
  { ID:'REQ-014', Req_Raised:'2026-02-25', HR_Approval_Date:'2026-03-02', Agreed_TAT:'2026-05-10', Request_DOJ:'', Vacancies:1, Status:'In Progress', Division:'Data Engineering', Function:'Engineering', Designation:'Lead Data Engineer', Location:'Bangalore', Requestor:'Rajan Pillai', Project:'Data Platform', TA_Members:'Priya Nair', Sourced:14, Shortlisted:4, In_Interview:2, Selected:1, Offered:1, Offer_Accepted:0, Joined:0 },
  { ID:'REQ-015', Req_Raised:'2026-03-10', HR_Approval_Date:'2026-03-15', Agreed_TAT:'2026-05-20', Request_DOJ:'', Vacancies:2, Status:'Open', Division:'Data Engineering', Function:'Engineering', Designation:'Data Engineer', Location:'Bangalore', Requestor:'Nisha Joshi', Project:'ETL Modernisation', TA_Members:'Priya Nair', Sourced:22, Shortlisted:5, In_Interview:2, Selected:0, Offered:0, Offer_Accepted:0, Joined:0 },
  { ID:'REQ-016', Req_Raised:'2026-04-05', HR_Approval_Date:'2026-04-10', Agreed_TAT:'2026-06-20', Request_DOJ:'', Vacancies:1, Status:'Open', Division:'Data Engineering', Function:'Engineering', Designation:'Data Architect', Location:'Mumbai', Requestor:'Rajan Pillai', Project:'Data Platform', TA_Members:'Priya Nair', Sourced:6, Shortlisted:2, In_Interview:1, Selected:0, Offered:0, Offer_Accepted:0, Joined:0 },
  { ID:'REQ-017', Req_Raised:'2026-04-18', HR_Approval_Date:'2026-04-22', Agreed_TAT:'2026-07-05', Request_DOJ:'', Vacancies:2, Status:'In Progress', Division:'Data Engineering', Function:'Engineering', Designation:'Senior Data Engineer', Location:'Hyderabad', Requestor:'Nisha Joshi', Project:'ETL Modernisation', TA_Members:'Priya Nair', Sourced:19, Shortlisted:5, In_Interview:3, Selected:1, Offered:1, Offer_Accepted:1, Joined:0 },
  { ID:'REQ-018', Req_Raised:'2026-06-01', HR_Approval_Date:'2026-06-06', Agreed_TAT:'2026-08-20', Request_DOJ:'', Vacancies:1, Status:'Open', Division:'Data Engineering', Function:'Engineering', Designation:'Data Engineer', Location:'Bangalore', Requestor:'Rajan Pillai', Project:'Data Platform', TA_Members:'Priya Nair', Sourced:9, Shortlisted:2, In_Interview:0, Selected:0, Offered:0, Offer_Accepted:0, Joined:0 },

  // ─── Content – Rahul Sharma ───────────────────────────────────────────────
  { ID:'REQ-019', Req_Raised:'2026-01-12', HR_Approval_Date:'2026-01-16', Agreed_TAT:'2026-03-10', Request_DOJ:'', Vacancies:3, Status:'Closed-Filled', Division:'Content', Function:'Content', Designation:'Content Writer', Location:'Delhi', Requestor:'Kavitha Subramanian', Project:'FS Content', TA_Members:'Rahul Sharma', Sourced:60, Shortlisted:18, In_Interview:8, Selected:3, Offered:3, Offer_Accepted:3, Joined:3 },
  { ID:'REQ-020', Req_Raised:'2026-01-25', HR_Approval_Date:'2026-01-30', Agreed_TAT:'2026-03-25', Request_DOJ:'', Vacancies:2, Status:'Closed-Filled', Division:'Content', Function:'Content', Designation:'Senior Content Writer', Location:'Mumbai', Requestor:'Kavitha Subramanian', Project:'Healthcare Content', TA_Members:'Rahul Sharma', Sourced:44, Shortlisted:12, In_Interview:5, Selected:2, Offered:2, Offer_Accepted:2, Joined:2 },
  { ID:'REQ-021', Req_Raised:'2026-02-08', HR_Approval_Date:'2026-02-13', Agreed_TAT:'2026-04-20', Request_DOJ:'', Vacancies:2, Status:'In Progress', Division:'Content', Function:'Content', Designation:'Content Writer', Location:'Delhi', Requestor:'Megha Singh', Project:'Retail Content', TA_Members:'Rahul Sharma', Sourced:48, Shortlisted:14, In_Interview:6, Selected:2, Offered:2, Offer_Accepted:1, Joined:0 },
  { ID:'REQ-022', Req_Raised:'2026-02-20', HR_Approval_Date:'2026-02-25', Agreed_TAT:'2026-04-28', Request_DOJ:'', Vacancies:1, Status:'In Progress', Division:'Content', Function:'Content', Designation:'Content Lead', Location:'Mumbai', Requestor:'Kavitha Subramanian', Project:'FS Content', TA_Members:'Rahul Sharma', Sourced:20, Shortlisted:6, In_Interview:3, Selected:1, Offered:1, Offer_Accepted:1, Joined:0 },
  { ID:'REQ-023', Req_Raised:'2026-03-05', HR_Approval_Date:'2026-03-10', Agreed_TAT:'2026-05-10', Request_DOJ:'', Vacancies:3, Status:'Cancelled', Division:'Content', Function:'Content', Designation:'Content Writer', Location:'Delhi', Requestor:'Megha Singh', Project:'Retail Content', TA_Members:'Rahul Sharma', Sourced:30, Shortlisted:8, In_Interview:3, Selected:0, Offered:0, Offer_Accepted:0, Joined:0 },
  { ID:'REQ-024', Req_Raised:'2026-03-18', HR_Approval_Date:'2026-03-24', Agreed_TAT:'2026-05-25', Request_DOJ:'', Vacancies:1, Status:'Open', Division:'Content', Function:'Content', Designation:'Content Manager', Location:'Delhi', Requestor:'Kavitha Subramanian', Project:'FS Content', TA_Members:'Rahul Sharma', Sourced:15, Shortlisted:4, In_Interview:2, Selected:0, Offered:0, Offer_Accepted:0, Joined:0 },
  { ID:'REQ-025', Req_Raised:'2026-04-10', HR_Approval_Date:'2026-04-15', Agreed_TAT:'2026-06-25', Request_DOJ:'', Vacancies:2, Status:'In Progress', Division:'Content', Function:'Content', Designation:'Senior Content Writer', Location:'Mumbai', Requestor:'Megha Singh', Project:'Healthcare Content', TA_Members:'Rahul Sharma', Sourced:36, Shortlisted:9, In_Interview:4, Selected:1, Offered:1, Offer_Accepted:0, Joined:0 },
  { ID:'REQ-026', Req_Raised:'2026-05-02', HR_Approval_Date:'2026-05-07', Agreed_TAT:'2026-07-15', Request_DOJ:'', Vacancies:3, Status:'Open', Division:'Content', Function:'Content', Designation:'Content Writer', Location:'Delhi', Requestor:'Kavitha Subramanian', Project:'Retail Content', TA_Members:'Rahul Sharma', Sourced:24, Shortlisted:6, In_Interview:2, Selected:0, Offered:0, Offer_Accepted:0, Joined:0 },
  { ID:'REQ-027', Req_Raised:'2026-06-10', HR_Approval_Date:'2026-06-15', Agreed_TAT:'2026-08-25', Request_DOJ:'', Vacancies:1, Status:'Open', Division:'Content', Function:'Content', Designation:'Content Writer', Location:'Mumbai', Requestor:'Megha Singh', Project:'FS Content', TA_Members:'Rahul Sharma', Sourced:8, Shortlisted:2, In_Interview:0, Selected:0, Offered:0, Offer_Accepted:0, Joined:0 },

  // ─── Technology Solutions – Meera Iyer ────────────────────────────────────
  { ID:'REQ-028', Req_Raised:'2026-01-14', HR_Approval_Date:'2026-01-20', Agreed_TAT:'2026-03-28', Request_DOJ:'', Vacancies:2, Status:'Closed-Filled', Division:'Technology Solutions', Function:'Technology', Designation:'Software Developer', Location:'Bangalore', Requestor:'Arun Krishnamurthy', Project:'TechOps Platform', TA_Members:'Meera Iyer', Sourced:35, Shortlisted:9, In_Interview:5, Selected:2, Offered:2, Offer_Accepted:2, Joined:2 },
  { ID:'REQ-029', Req_Raised:'2026-02-01', HR_Approval_Date:'2026-02-07', Agreed_TAT:'2026-04-15', Request_DOJ:'', Vacancies:1, Status:'Closed-Filled', Division:'Technology Solutions', Function:'Technology', Designation:'Tech Lead', Location:'Mumbai', Requestor:'Arun Krishnamurthy', Project:'TechOps Platform', TA_Members:'Meera Iyer', Sourced:18, Shortlisted:5, In_Interview:3, Selected:1, Offered:1, Offer_Accepted:1, Joined:1 },
  { ID:'REQ-030', Req_Raised:'2026-02-18', HR_Approval_Date:'2026-02-24', Agreed_TAT:'2026-04-30', Request_DOJ:'', Vacancies:3, Status:'In Progress', Division:'Technology Solutions', Function:'Technology', Designation:'Software Developer', Location:'Bangalore', Requestor:'Shriya Patel', Project:'Digital Transformation', TA_Members:'Meera Iyer', Sourced:46, Shortlisted:12, In_Interview:6, Selected:2, Offered:2, Offer_Accepted:1, Joined:0 },
  { ID:'REQ-031', Req_Raised:'2026-03-08', HR_Approval_Date:'2026-03-13', Agreed_TAT:'2026-05-15', Request_DOJ:'', Vacancies:1, Status:'In Progress', Division:'Technology Solutions', Function:'Technology', Designation:'Solutions Architect', Location:'Bangalore', Requestor:'Arun Krishnamurthy', Project:'TechOps Platform', TA_Members:'Meera Iyer', Sourced:10, Shortlisted:3, In_Interview:2, Selected:1, Offered:1, Offer_Accepted:1, Joined:0 },
  { ID:'REQ-032', Req_Raised:'2026-03-22', HR_Approval_Date:'2026-03-27', Agreed_TAT:'2026-06-05', Request_DOJ:'', Vacancies:2, Status:'Open', Division:'Technology Solutions', Function:'Technology', Designation:'Senior Developer', Location:'Hyderabad', Requestor:'Shriya Patel', Project:'Digital Transformation', TA_Members:'Meera Iyer', Sourced:20, Shortlisted:5, In_Interview:2, Selected:0, Offered:0, Offer_Accepted:0, Joined:0 },
  { ID:'REQ-033', Req_Raised:'2026-04-15', HR_Approval_Date:'2026-04-20', Agreed_TAT:'2026-06-28', Request_DOJ:'', Vacancies:1, Status:'Open', Division:'Technology Solutions', Function:'Technology', Designation:'Software Developer', Location:'Mumbai', Requestor:'Arun Krishnamurthy', Project:'TechOps Platform', TA_Members:'Meera Iyer', Sourced:14, Shortlisted:4, In_Interview:2, Selected:0, Offered:0, Offer_Accepted:0, Joined:0 },
  { ID:'REQ-034', Req_Raised:'2026-06-05', HR_Approval_Date:'2026-06-10', Agreed_TAT:'2026-08-20', Request_DOJ:'', Vacancies:2, Status:'Open', Division:'Technology Solutions', Function:'Technology', Designation:'Software Developer', Location:'Bangalore', Requestor:'Shriya Patel', Project:'Digital Transformation', TA_Members:'Meera Iyer', Sourced:10, Shortlisted:2, In_Interview:0, Selected:0, Offered:0, Offer_Accepted:0, Joined:0 },

  // ─── CoE – Meera Iyer ─────────────────────────────────────────────────────
  { ID:'REQ-035', Req_Raised:'2026-01-20', HR_Approval_Date:'2026-01-25', Agreed_TAT:'2026-03-30', Request_DOJ:'', Vacancies:2, Status:'Closed-Filled', Division:'CoE', Function:'Analytics', Designation:'Research Analyst', Location:'Mumbai', Requestor:'Ganesh Rao', Project:'CoE Analytics', TA_Members:'Meera Iyer', Sourced:40, Shortlisted:10, In_Interview:5, Selected:2, Offered:2, Offer_Accepted:2, Joined:2 },
  { ID:'REQ-036', Req_Raised:'2026-02-12', HR_Approval_Date:'2026-02-18', Agreed_TAT:'2026-04-25', Request_DOJ:'', Vacancies:1, Status:'In Progress', Division:'CoE', Function:'Analytics', Designation:'Senior Research Analyst', Location:'Mumbai', Requestor:'Ganesh Rao', Project:'CoE Analytics', TA_Members:'Meera Iyer', Sourced:22, Shortlisted:6, In_Interview:3, Selected:1, Offered:1, Offer_Accepted:1, Joined:0 },
  { ID:'REQ-037', Req_Raised:'2026-03-25', HR_Approval_Date:'2026-03-30', Agreed_TAT:'2026-06-10', Request_DOJ:'', Vacancies:2, Status:'Open', Division:'CoE', Function:'Analytics', Designation:'Data Analyst', Location:'Bangalore', Requestor:'Ganesh Rao', Project:'CoE Data', TA_Members:'Meera Iyer', Sourced:16, Shortlisted:4, In_Interview:1, Selected:0, Offered:0, Offer_Accepted:0, Joined:0 },
  { ID:'REQ-038', Req_Raised:'2026-04-28', HR_Approval_Date:'2026-05-04', Agreed_TAT:'2026-07-15', Request_DOJ:'', Vacancies:1, Status:'Open', Division:'CoE', Function:'Analytics', Designation:'Analytics Manager', Location:'Mumbai', Requestor:'Ganesh Rao', Project:'CoE Analytics', TA_Members:'Meera Iyer', Sourced:7, Shortlisted:2, In_Interview:1, Selected:0, Offered:0, Offer_Accepted:0, Joined:0 },
  { ID:'REQ-039', Req_Raised:'2026-06-15', HR_Approval_Date:'', Agreed_TAT:'', Request_DOJ:'2026-09-01', Vacancies:2, Status:'Draft/Unapproved', Division:'CoE', Function:'Analytics', Designation:'Research Analyst', Location:'Mumbai', Requestor:'Ganesh Rao', Project:'CoE Analytics', TA_Members:'', Sourced:0, Shortlisted:0, In_Interview:0, Selected:0, Offered:0, Offer_Accepted:0, Joined:0 },

  // ─── Sales – Vikram Patel ─────────────────────────────────────────────────
  { ID:'REQ-040', Req_Raised:'2026-01-16', HR_Approval_Date:'2026-01-22', Agreed_TAT:'2026-03-25', Request_DOJ:'', Vacancies:2, Status:'Closed-Filled', Division:'Sales', Function:'Sales', Designation:'Sales Manager', Location:'Mumbai', Requestor:'Rajesh Malhotra', Project:'Sales Expansion', TA_Members:'Vikram Patel', Sourced:30, Shortlisted:8, In_Interview:4, Selected:2, Offered:2, Offer_Accepted:2, Joined:2 },
  { ID:'REQ-041', Req_Raised:'2026-02-05', HR_Approval_Date:'2026-02-10', Agreed_TAT:'2026-04-10', Request_DOJ:'', Vacancies:1, Status:'Cancelled', Division:'Sales', Function:'Sales', Designation:'Senior Sales Executive', Location:'Delhi', Requestor:'Rajesh Malhotra', Project:'Sales Expansion', TA_Members:'Vikram Patel', Sourced:15, Shortlisted:4, In_Interview:2, Selected:0, Offered:0, Offer_Accepted:0, Joined:0 },
  { ID:'REQ-042', Req_Raised:'2026-03-10', HR_Approval_Date:'2026-03-16', Agreed_TAT:'2026-05-20', Request_DOJ:'', Vacancies:2, Status:'In Progress', Division:'Sales', Function:'Sales', Designation:'Sales Executive', Location:'Mumbai', Requestor:'Rajesh Malhotra', Project:'Sales Expansion', TA_Members:'Vikram Patel', Sourced:22, Shortlisted:6, In_Interview:3, Selected:1, Offered:1, Offer_Accepted:0, Joined:0 },
  { ID:'REQ-043', Req_Raised:'2026-04-20', HR_Approval_Date:'2026-04-25', Agreed_TAT:'2026-07-01', Request_DOJ:'', Vacancies:1, Status:'Open', Division:'Sales', Function:'Sales', Designation:'Account Manager', Location:'Bangalore', Requestor:'Rajesh Malhotra', Project:'Sales Expansion', TA_Members:'Vikram Patel', Sourced:10, Shortlisted:3, In_Interview:1, Selected:0, Offered:0, Offer_Accepted:0, Joined:0 },
  { ID:'REQ-044', Req_Raised:'2026-06-01', HR_Approval_Date:'2026-06-06', Agreed_TAT:'2026-08-15', Request_DOJ:'', Vacancies:1, Status:'Open', Division:'Sales', Function:'Sales', Designation:'Sales Manager', Location:'Mumbai', Requestor:'Rajesh Malhotra', Project:'New Verticals', TA_Members:'Vikram Patel', Sourced:4, Shortlisted:1, In_Interview:0, Selected:0, Offered:0, Offer_Accepted:0, Joined:0 },

  // ─── Business Development – Vikram Patel ──────────────────────────────────
  { ID:'REQ-045', Req_Raised:'2026-01-28', HR_Approval_Date:'2026-02-03', Agreed_TAT:'2026-04-05', Request_DOJ:'', Vacancies:2, Status:'Closed-Filled', Division:'Business Development', Function:'BD', Designation:'BD Manager', Location:'Mumbai', Requestor:'Suresh Iyer', Project:'Global BD', TA_Members:'Vikram Patel', Sourced:28, Shortlisted:7, In_Interview:4, Selected:2, Offered:2, Offer_Accepted:2, Joined:2 },
  { ID:'REQ-046', Req_Raised:'2026-02-22', HR_Approval_Date:'2026-02-27', Agreed_TAT:'2026-05-05', Request_DOJ:'', Vacancies:1, Status:'In Progress', Division:'Business Development', Function:'BD', Designation:'Senior BD Executive', Location:'Delhi', Requestor:'Suresh Iyer', Project:'Global BD', TA_Members:'Vikram Patel', Sourced:16, Shortlisted:5, In_Interview:2, Selected:1, Offered:1, Offer_Accepted:1, Joined:0 },
  { ID:'REQ-047', Req_Raised:'2026-04-10', HR_Approval_Date:'2026-04-15', Agreed_TAT:'2026-06-25', Request_DOJ:'', Vacancies:1, Status:'Open', Division:'Business Development', Function:'BD', Designation:'BD Analyst', Location:'Mumbai', Requestor:'Suresh Iyer', Project:'Global BD', TA_Members:'Vikram Patel', Sourced:8, Shortlisted:2, In_Interview:0, Selected:0, Offered:0, Offer_Accepted:0, Joined:0 },
  { ID:'REQ-048', Req_Raised:'2026-05-15', HR_Approval_Date:'2026-05-20', Agreed_TAT:'2026-08-01', Request_DOJ:'', Vacancies:2, Status:'Open', Division:'Business Development', Function:'BD', Designation:'BD Manager', Location:'Mumbai', Requestor:'Suresh Iyer', Project:'New Markets', TA_Members:'Vikram Patel', Sourced:6, Shortlisted:2, In_Interview:1, Selected:0, Offered:0, Offer_Accepted:0, Joined:0 },

  // ─── Marketing – Rahul Sharma ─────────────────────────────────────────────
  { ID:'REQ-049', Req_Raised:'2026-02-05', HR_Approval_Date:'2026-02-10', Agreed_TAT:'2026-04-15', Request_DOJ:'', Vacancies:1, Status:'Closed-Filled', Division:'Marketing', Function:'Marketing', Designation:'Marketing Manager', Location:'Mumbai', Requestor:'Ananya Krishnan', Project:'Brand Marketing', TA_Members:'Rahul Sharma', Sourced:20, Shortlisted:5, In_Interview:3, Selected:1, Offered:1, Offer_Accepted:1, Joined:1 },
  { ID:'REQ-050', Req_Raised:'2026-03-12', HR_Approval_Date:'2026-03-17', Agreed_TAT:'2026-05-25', Request_DOJ:'', Vacancies:2, Status:'In Progress', Division:'Marketing', Function:'Marketing', Designation:'Content Marketing Specialist', Location:'Delhi', Requestor:'Ananya Krishnan', Project:'Digital Marketing', TA_Members:'Rahul Sharma', Sourced:28, Shortlisted:8, In_Interview:3, Selected:1, Offered:1, Offer_Accepted:0, Joined:0 },
  { ID:'REQ-051', Req_Raised:'2026-05-08', HR_Approval_Date:'2026-05-13', Agreed_TAT:'2026-07-25', Request_DOJ:'', Vacancies:1, Status:'Open', Division:'Marketing', Function:'Marketing', Designation:'Digital Marketing Analyst', Location:'Mumbai', Requestor:'Ananya Krishnan', Project:'Digital Marketing', TA_Members:'Rahul Sharma', Sourced:11, Shortlisted:3, In_Interview:1, Selected:0, Offered:0, Offer_Accepted:0, Joined:0 },
  { ID:'REQ-052', Req_Raised:'2026-07-01', HR_Approval_Date:'2026-07-07', Agreed_TAT:'2026-09-15', Request_DOJ:'', Vacancies:1, Status:'Open', Division:'Marketing', Function:'Marketing', Designation:'Marketing Manager', Location:'Mumbai', Requestor:'Ananya Krishnan', Project:'Brand Marketing', TA_Members:'Rahul Sharma', Sourced:5, Shortlisted:1, In_Interview:0, Selected:0, Offered:0, Offer_Accepted:0, Joined:0 },

  // ─── Admin – Anitha Rao ────────────────────────────────────────────────────
  { ID:'REQ-053', Req_Raised:'2026-01-05', HR_Approval_Date:'2026-01-09', Agreed_TAT:'2026-03-01', Request_DOJ:'', Vacancies:1, Status:'Closed-Filled', Division:'Admin', Function:'Administration', Designation:'Executive Assistant', Location:'Mumbai', Requestor:'Aditya Sharma', Project:'Corporate', TA_Members:'Anitha Rao', Sourced:25, Shortlisted:7, In_Interview:3, Selected:1, Offered:1, Offer_Accepted:1, Joined:1 },
  { ID:'REQ-054', Req_Raised:'2026-02-28', HR_Approval_Date:'2026-03-05', Agreed_TAT:'2026-05-15', Request_DOJ:'', Vacancies:2, Status:'In Progress', Division:'Admin', Function:'Administration', Designation:'Admin Executive', Location:'Mumbai', Requestor:'Aditya Sharma', Project:'Corporate', TA_Members:'Anitha Rao', Sourced:18, Shortlisted:5, In_Interview:3, Selected:1, Offered:1, Offer_Accepted:1, Joined:0 },
  { ID:'REQ-055', Req_Raised:'2026-05-20', HR_Approval_Date:'2026-05-25', Agreed_TAT:'2026-08-01', Request_DOJ:'', Vacancies:1, Status:'Open', Division:'Admin', Function:'Administration', Designation:'Office Manager', Location:'Bangalore', Requestor:'Aditya Sharma', Project:'Corporate', TA_Members:'Anitha Rao', Sourced:8, Shortlisted:2, In_Interview:0, Selected:0, Offered:0, Offer_Accepted:0, Joined:0 },

  // ─── Finance – Anitha Rao ─────────────────────────────────────────────────
  { ID:'REQ-056', Req_Raised:'2026-01-20', HR_Approval_Date:'2026-01-25', Agreed_TAT:'2026-03-20', Request_DOJ:'', Vacancies:1, Status:'Closed-Filled', Division:'Finance', Function:'Finance', Designation:'Finance Analyst', Location:'Mumbai', Requestor:'Vikrant Bose', Project:'Finance Ops', TA_Members:'Anitha Rao', Sourced:30, Shortlisted:8, In_Interview:4, Selected:1, Offered:1, Offer_Accepted:1, Joined:1 },
  { ID:'REQ-057', Req_Raised:'2026-04-05', HR_Approval_Date:'2026-04-10', Agreed_TAT:'2026-06-20', Request_DOJ:'', Vacancies:1, Status:'In Progress', Division:'Finance', Function:'Finance', Designation:'Senior Finance Analyst', Location:'Mumbai', Requestor:'Vikrant Bose', Project:'Finance Ops', TA_Members:'Anitha Rao', Sourced:16, Shortlisted:4, In_Interview:2, Selected:1, Offered:1, Offer_Accepted:0, Joined:0 },
  { ID:'REQ-058', Req_Raised:'2026-07-10', HR_Approval_Date:'2026-07-15', Agreed_TAT:'2026-09-25', Request_DOJ:'', Vacancies:1, Status:'Open', Division:'Finance', Function:'Finance', Designation:'Finance Manager', Location:'Mumbai', Requestor:'Vikrant Bose', Project:'Finance Ops', TA_Members:'Anitha Rao', Sourced:4, Shortlisted:1, In_Interview:0, Selected:0, Offered:0, Offer_Accepted:0, Joined:0 },

  // ─── PMO – Anitha Rao ─────────────────────────────────────────────────────
  { ID:'REQ-059', Req_Raised:'2026-02-10', HR_Approval_Date:'2026-02-15', Agreed_TAT:'2026-04-20', Request_DOJ:'', Vacancies:1, Status:'Cancelled', Division:'PMO', Function:'PMO', Designation:'Project Manager', Location:'Mumbai', Requestor:'Rekha Nambiar', Project:'PMO Ops', TA_Members:'Anitha Rao', Sourced:12, Shortlisted:3, In_Interview:1, Selected:0, Offered:0, Offer_Accepted:0, Joined:0 },
  { ID:'REQ-060', Req_Raised:'2026-04-22', HR_Approval_Date:'2026-04-28', Agreed_TAT:'2026-07-10', Request_DOJ:'', Vacancies:2, Status:'Open', Division:'PMO', Function:'PMO', Designation:'Project Coordinator', Location:'Mumbai', Requestor:'Rekha Nambiar', Project:'PMO Ops', TA_Members:'Anitha Rao', Sourced:6, Shortlisted:2, In_Interview:0, Selected:0, Offered:0, Offer_Accepted:0, Joined:0 },

  // ─── Legal – Anitha Rao ───────────────────────────────────────────────────
  { ID:'REQ-061', Req_Raised:'2026-03-01', HR_Approval_Date:'2026-03-06', Agreed_TAT:'2026-05-15', Request_DOJ:'', Vacancies:1, Status:'In Progress', Division:'Legal', Function:'Legal', Designation:'Legal Counsel', Location:'Mumbai', Requestor:'Arjun Menon', Project:'Legal Compliance', TA_Members:'Anitha Rao', Sourced:8, Shortlisted:2, In_Interview:1, Selected:1, Offered:1, Offer_Accepted:1, Joined:0 },
  { ID:'REQ-062', Req_Raised:'2026-06-20', HR_Approval_Date:'2026-06-25', Agreed_TAT:'2026-09-05', Request_DOJ:'', Vacancies:1, Status:'Open', Division:'Legal', Function:'Legal', Designation:'Legal Analyst', Location:'Mumbai', Requestor:'Arjun Menon', Project:'Legal Compliance', TA_Members:'Anitha Rao', Sourced:5, Shortlisted:1, In_Interview:0, Selected:0, Offered:0, Offer_Accepted:0, Joined:0 },

  // ─── Unassigned / No TA ───────────────────────────────────────────────────
  { ID:'REQ-063', Req_Raised:'2026-01-30', HR_Approval_Date:'2026-02-05', Agreed_TAT:'2026-04-10', Request_DOJ:'', Vacancies:2, Status:'Cancelled', Division:'Data Analytics', Function:'Analytics', Designation:'Research Analyst', Location:'Mumbai', Requestor:'Abhijit Gupta', Project:'Client Intel', TA_Members:'', Sourced:0, Shortlisted:0, In_Interview:0, Selected:0, Offered:0, Offer_Accepted:0, Joined:0 },
  { ID:'REQ-064', Req_Raised:'2026-02-15', HR_Approval_Date:'2026-02-20', Agreed_TAT:'2026-04-20', Request_DOJ:'', Vacancies:1, Status:'Rejected@Approval', Division:'Technology Solutions', Function:'Technology', Designation:'Senior Developer', Location:'Bangalore', Requestor:'Arun Krishnamurthy', Project:'Digital Transformation', TA_Members:'', Sourced:0, Shortlisted:0, In_Interview:0, Selected:0, Offered:0, Offer_Accepted:0, Joined:0 },
  { ID:'REQ-065', Req_Raised:'2026-03-01', HR_Approval_Date:'2026-03-07', Agreed_TAT:'2026-05-10', Request_DOJ:'', Vacancies:3, Status:'Open', Division:'Data Engineering', Function:'Engineering', Designation:'Data Engineer', Location:'Hyderabad', Requestor:'Nisha Joshi', Project:'ETL Modernisation', TA_Members:'', Sourced:10, Shortlisted:3, In_Interview:1, Selected:0, Offered:0, Offer_Accepted:0, Joined:0 },
  { ID:'REQ-066', Req_Raised:'2026-03-20', HR_Approval_Date:'2026-03-25', Agreed_TAT:'2026-05-30', Request_DOJ:'', Vacancies:1, Status:'In Progress', Division:'CoE', Function:'Analytics', Designation:'Data Analyst', Location:'Mumbai', Requestor:'Ganesh Rao', Project:'CoE Data', TA_Members:'', Sourced:14, Shortlisted:4, In_Interview:2, Selected:0, Offered:0, Offer_Accepted:0, Joined:0 },
  { ID:'REQ-067', Req_Raised:'2026-04-08', HR_Approval_Date:'2026-04-12', Agreed_TAT:'2026-06-20', Request_DOJ:'', Vacancies:2, Status:'Open', Division:'Content', Function:'Content', Designation:'Content Writer', Location:'Delhi', Requestor:'Megha Singh', Project:'Retail Content', TA_Members:'', Sourced:5, Shortlisted:1, In_Interview:0, Selected:0, Offered:0, Offer_Accepted:0, Joined:0 },
  { ID:'REQ-068', Req_Raised:'2026-05-01', HR_Approval_Date:'2026-05-06', Agreed_TAT:'2026-07-20', Request_DOJ:'', Vacancies:1, Status:'Rejected@Approval', Division:'Sales', Function:'Sales', Designation:'Sales Manager', Location:'Mumbai', Requestor:'Rajesh Malhotra', Project:'New Verticals', TA_Members:'', Sourced:0, Shortlisted:0, In_Interview:0, Selected:0, Offered:0, Offer_Accepted:0, Joined:0 },
  { ID:'REQ-069', Req_Raised:'2026-06-08', HR_Approval_Date:'2026-06-12', Agreed_TAT:'', Request_DOJ:'2026-09-01', Vacancies:2, Status:'Open', Division:'Data Analytics', Function:'Analytics', Designation:'Research Analyst', Location:'Bangalore', Requestor:'Prashant Mehta', Project:'BFSI Research', TA_Members:'', Sourced:3, Shortlisted:0, In_Interview:0, Selected:0, Offered:0, Offer_Accepted:0, Joined:0 },
  { ID:'REQ-070', Req_Raised:'2026-07-05', HR_Approval_Date:'2026-07-10', Agreed_TAT:'2026-09-30', Request_DOJ:'', Vacancies:1, Status:'Open', Division:'Data Engineering', Function:'Engineering', Designation:'Data Engineer', Location:'Bangalore', Requestor:'Rajan Pillai', Project:'Data Platform', TA_Members:'', Sourced:2, Shortlisted:0, In_Interview:0, Selected:0, Offered:0, Offer_Accepted:0, Joined:0 },

  // ─── Breached reqs (ageing > agreed TAT) ──────────────────────────────────
  { ID:'REQ-071', Req_Raised:'2025-11-01', HR_Approval_Date:'2025-11-06', Agreed_TAT:'2026-01-31', Request_DOJ:'', Vacancies:2, Status:'In Progress', Division:'Data Analytics', Function:'Analytics', Designation:'Senior Research Analyst', Location:'Mumbai', Requestor:'Abhijit Gupta', Project:'Strategic Research', TA_Members:'Priya Nair', Sourced:38, Shortlisted:10, In_Interview:5, Selected:1, Offered:1, Offer_Accepted:0, Joined:0 },
  { ID:'REQ-072', Req_Raised:'2025-11-15', HR_Approval_Date:'2025-11-20', Agreed_TAT:'2026-02-15', Request_DOJ:'', Vacancies:1, Status:'In Progress', Division:'Data Engineering', Function:'Engineering', Designation:'Lead Data Engineer', Location:'Bangalore', Requestor:'Rajan Pillai', Project:'Data Platform', TA_Members:'Priya Nair', Sourced:12, Shortlisted:4, In_Interview:2, Selected:0, Offered:0, Offer_Accepted:0, Joined:0 },
  { ID:'REQ-073', Req_Raised:'2025-12-01', HR_Approval_Date:'2025-12-06', Agreed_TAT:'2026-02-28', Request_DOJ:'', Vacancies:3, Status:'In Progress', Division:'Content', Function:'Content', Designation:'Content Writer', Location:'Delhi', Requestor:'Kavitha Subramanian', Project:'FS Content', TA_Members:'Rahul Sharma', Sourced:55, Shortlisted:15, In_Interview:7, Selected:2, Offered:2, Offer_Accepted:1, Joined:0 },
  { ID:'REQ-074', Req_Raised:'2025-12-10', HR_Approval_Date:'2025-12-15', Agreed_TAT:'2026-03-15', Request_DOJ:'', Vacancies:1, Status:'In Progress', Division:'Technology Solutions', Function:'Technology', Designation:'Tech Lead', Location:'Bangalore', Requestor:'Arun Krishnamurthy', Project:'TechOps Platform', TA_Members:'Meera Iyer', Sourced:10, Shortlisted:3, In_Interview:2, Selected:1, Offered:1, Offer_Accepted:1, Joined:0 },
  { ID:'REQ-075', Req_Raised:'2025-12-20', HR_Approval_Date:'2025-12-26', Agreed_TAT:'2026-03-20', Request_DOJ:'', Vacancies:2, Status:'In Progress', Division:'CoE', Function:'Analytics', Designation:'Data Analyst', Location:'Mumbai', Requestor:'Ganesh Rao', Project:'CoE Analytics', TA_Members:'Meera Iyer', Sourced:28, Shortlisted:7, In_Interview:3, Selected:1, Offered:1, Offer_Accepted:1, Joined:0 },

  // ─── Inferred TAT only (no agreed_tat, using request_doj) ─────────────────
  { ID:'REQ-076', Req_Raised:'2026-02-20', HR_Approval_Date:'2026-02-26', Agreed_TAT:'', Request_DOJ:'2026-05-15', Vacancies:2, Status:'In Progress', Division:'Data Analytics', Function:'Analytics', Designation:'Data Analyst', Location:'Bangalore', Requestor:'Sonal Kapoor', Project:'E-comm Intelligence', TA_Members:'Priya Nair', Sourced:22, Shortlisted:6, In_Interview:3, Selected:1, Offered:1, Offer_Accepted:0, Joined:0 },
  { ID:'REQ-077', Req_Raised:'2026-03-15', HR_Approval_Date:'2026-03-20', Agreed_TAT:'', Request_DOJ:'2026-06-01', Vacancies:1, Status:'Open', Division:'Data Engineering', Function:'Engineering', Designation:'Senior Data Engineer', Location:'Hyderabad', Requestor:'Nisha Joshi', Project:'ETL Modernisation', TA_Members:'Priya Nair', Sourced:8, Shortlisted:2, In_Interview:0, Selected:0, Offered:0, Offer_Accepted:0, Joined:0 },
  { ID:'REQ-078', Req_Raised:'2026-04-01', HR_Approval_Date:'2026-04-07', Agreed_TAT:'', Request_DOJ:'2026-07-01', Vacancies:2, Status:'Open', Division:'Content', Function:'Content', Designation:'Content Writer', Location:'Delhi', Requestor:'Megha Singh', Project:'Healthcare Content', TA_Members:'Rahul Sharma', Sourced:14, Shortlisted:4, In_Interview:1, Selected:0, Offered:0, Offer_Accepted:0, Joined:0 },
  { ID:'REQ-079', Req_Raised:'2026-04-15', HR_Approval_Date:'2026-04-20', Agreed_TAT:'', Request_DOJ:'2026-07-15', Vacancies:1, Status:'In Progress', Division:'Business Development', Function:'BD', Designation:'BD Manager', Location:'Mumbai', Requestor:'Suresh Iyer', Project:'New Markets', TA_Members:'Vikram Patel', Sourced:6, Shortlisted:2, In_Interview:1, Selected:0, Offered:0, Offer_Accepted:0, Joined:0 },
  { ID:'REQ-080', Req_Raised:'2026-05-10', HR_Approval_Date:'2026-05-15', Agreed_TAT:'', Request_DOJ:'2026-08-10', Vacancies:1, Status:'Open', Division:'PMO', Function:'PMO', Designation:'Project Manager', Location:'Mumbai', Requestor:'Rekha Nambiar', Project:'PMO Ops', TA_Members:'Anitha Rao', Sourced:3, Shortlisted:1, In_Interview:0, Selected:0, Offered:0, Offer_Accepted:0, Joined:0 },
];

export function getSampleCSV(): string {
  const headers = Object.keys(ROWS[0]).join(',');
  const rows = ROWS.map(r =>
    Object.values(r).map(v => {
      const s = String(v ?? '');
      return s.includes(',') ? `"${s}"` : s;
    }).join(',')
  );
  return [headers, ...rows].join('\n');
}

export function getSampleRows(): SampleRow[] {
  return ROWS;
}
